dist: trusty
sudo: required

language: python

services:
  - docker

python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  - CHAINER_VERSION=3.5.0
  - CHAINER_VERSION=4.2.0

notifications:
  email: false

before_install:
  - docker pull mitmul/onnx-chainer:python${TRAVIS_PYTHON_VERSION}-chainer${CHAINER_VERSION}

script:
  - bash docker/run_tests.sh
