sudo: required

language: python

services:
  - docker

  python:
  - "2.7"
  - "3.6"

  env:
  - CHAINER_VERSION="==4.0.0"

notifications:
  email: false

before_install:
- docker pull mitmul/onnx-chainer:v$CHAINER_VERSION-py$TRAVIS_PYTHON_VERSION

addons:
  apt:
    packages:
      - build-essential
      - curl
      - git

script:
  - docker run -v $TRAVIS_BUILD_DIR:/root/onnx-chainer --rm -ti mitmul/onnx-chainer:v$CHAINER_VERSION-py$TRAVIS_PYTHON_VERSION \
    cd /root/onnx-chainer && flake8 . && \
    autopep8 -r -d . | tee check_autopep8 && \
    test ! -s check_autopep8 && \
    py.test -vvvs tests && \
